_target_: fivegsim.platforms.odroid_acc.OdroidWithAccelerators
# Once hydra 1.1 rolls out with recursive instantiation,
# we should replace this and recursively instantiate
# the processors. See:
# https://github.com/facebookresearch/hydra/issues/566
processor_0:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'ARM_CORTEX_A7'
  frequency : 1500000000
  static_power: 0.1403
  dynamic_power: 0.3202
processor_1:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'ARM_CORTEX_A15'
  frequency : 1800000000
  static_power: 0.2148
  dynamic_power: 1.3196
processor_fft_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc_fft,ifftm,iffta'
  frequency : 300000000
  static_power: 0.3125
  dynamic_power: 0.0625
num_big : 4
num_little : 4
num_fft_acc : 2
# The static power not included in the processors
peripheral_static_power: 0.7633
name: 'odroid_acc'
symmetries_json: null
embedding_json: null
