_target_: fivegsim.platforms.odroid_acc.OdroidWithAccelerators
# Once hydra 1.1 rolls out with recursive instantiation,
# we should replace this and recursively instantiate
# the processors. See:
# https://github.com/facebookresearch/hydra/issues/566
processor_0:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'ARM_CORTEX_A7'
  frequency : 1500000000
  static_power: 0.1403
  dynamic_power: 0.3202
processor_1:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'ARM_CORTEX_A15'
  frequency : 1800000000
  static_power: 0.2148
  dynamic_power: 1.3196
processor_fft_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:fft,ifftm,iffta'
  frequency : 250000000
  static_power: 0.3125
  dynamic_power: 0.0625
processor_mf_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:mf'
  frequency : 250000000
  static_power: 0.15625
  dynamic_power: 0.0625
processor_wind_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:wind'
  frequency : 250000000
  static_power: 0.15625
  dynamic_power: 0.0625
processor_ant_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:ant'
  frequency : 250000000
  static_power: 0.21875
  dynamic_power: 0.0625
processor_comb_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:comb'
  frequency : 250000000
  static_power: 0.21875
  dynamic_power: 0.0625
processor_demap1_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:demap1'
  frequency : 250000000
  static_power: 0.1875
  dynamic_power: 0.0625
processor_demap2_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:demap2'
  frequency : 250000000
  static_power: 0.1875
  dynamic_power: 0.0625
processor_demap4_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:demap4'
  frequency : 250000000
  static_power: 0.1875
  dynamic_power: 0.0625
processor_demap6_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type : 'acc:demap6'
  frequency : 250000000
  static_power: 0.1875
  dynamic_power: 0.0625
processor_demap8_acc:
  _target_: mocasin.platforms.platformDesigner.genericProcessor
  type: 'acc:demap8'
  frequency: 250000000
  static_power: 0.1875
  dynamic_power: 0.0625
num_big : 4
num_little : 4
num_fft_acc : 2
num_mf_acc : 0
num_wind_acc : 0
num_ant_acc : 0
num_comb_acc : 0
num_demap0_acc : 0
num_demap1_acc : 0
num_demap2_acc : 0
num_demap3_acc : 0
num_demap4_acc : 0
# The static power not included in the processors
peripheral_static_power: 0.7633
name: 'odroid_acc'
symmetries_json: null
embedding_json: null
