variables:
  # The mocasin branch to clone. We set the default to the current ref of this
  # repository, but this variable can be overwritten by an upstream pipeline.
  MOCASIN_BRANCH: $CI_COMMIT_REF_NAME
  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - maintenance
  - build
  - test

# keep a separate master-ci branch that mirrors the master branch. This helps
# with multi-project pipelines. So the upstream pipeline in mocasin can trigger
# the local pipeline on the master-ci branch with interfering with other local
# pipelines run on master.
mirror-ci-branch:
  stage: maintenance
  script:
    - git push -o ci.skip https://project_206_bot1:${CI_ACCESS_TOKEN}@cc.inf.tu-dresden.de/gitlab/mocasin/fivegsim HEAD:master-ci
  only:
    - master
  tags:
    - python3.9

.build:
  script:
    # install dependencies for builing mpsym and qdldl from source
    - apt-get update
    - apt-get install -y build-essential cmake libboost-dev libboost-graph-dev lua5.3 liblua5.3-dev luarocks
    # Clone mocasin from branch $MOCASIN_BRANCH or master if the branch does not exist
    - git clone -b $MOCASIN_BRANCH https://gitlab-ci-token:${CI_JOB_TOKEN}@cc.inf.tu-dresden.de/gitlab/mocasin/mocasin /tmp/mocasin || git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@cc.inf.tu-dresden.de/gitlab/mocasin/mocasin /tmp/mocasin
    # build the wheels
    - pip wheel -w wheels /tmp/mocasin .
  artifacts:
    paths:
      - wheels
  # make pip's cache persistent across pipelines
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .cache/pip

build-python3.10:
  extends: .build
  stage: build
  image: python:3.10
  tags:
    - python3.10

build-python3.9:
  extends: .build
  stage: build
  image: python:3.9
  tags:
    - python3.9

build-python3.8:
  extends: .build
  stage: build
  image: python:3.8
  tags:
    - python3.8

build-python3.7:
  extends: .build
  stage: build
  image: python:3.7
  tags:
    - python3.7

build-python3.6:
  extends: .build
  stage: build
  image: python:3.6
  tags:
    - python3.6

.test:
  script:
    # install runtime dependencies for mpsym
    - apt-get update
    - apt-get install -y lua5.3 liblua5.3 luarocks
    # retrieve pynauty from upstream job
    - 'curl --location --output pynauty.zip --header "PRIVATE-TOKEN: ${CI_ACCESS_TOKEN}" "https://cc.inf.tu-dresden.de/gitlab/api/v4/projects/26/jobs/artifacts/master/download?job=$PYNAUTY_JOB"' 
    - file pynauty.zip
    - unzip pynauty.zip
    - pip install pynauty*.whl
    - pip install mocasin*.whl
    - pip install fivegsim*.whl
    - if [ "${CI_PIPELINE_SOURCE}" == "pipeline" ]; then git checkout origin/$MOCASIN_BRANCH || true; fi
    # run tests
    - python setup.py test

.test:
  script:
    - pip install fivegsim --no-index --find-links=./wheels
    - python setup.py test

test-python3.10:
  extends: .test
  stage: test
  image: python:3.10
  tags:
    - python3.10
  needs:
    - build-python3.10

test-python3.9:
  extends: .test
  stage: test
  image: python:3.9
  tags:
    - python3.9
  needs:
    - build-python3.9

test-python3.8:
  extends: .test
  stage: test
  image: python:3.8
  tags:
    - python3.8
  needs:
    - build-python3.8

test-python3.7:
  extends: .test
  stage: test
  image: python:3.7
  tags:
    - python3.7
  needs:
    - build-python3.7

test-python3.6:
  extends: .test
  stage: test
  image: python:3.6
  tags:
    - python3.6
  needs:
    - build-python3.6

check-formatting:
  stage: test
  image: python:3.9
  tags:
    - python3.9
  needs: []
  script:
    - pip install black
    - black --check .
