# @package _global_
trace_file: "${fivegsim_path:files/slicedtrace30BS.txt}"
task_file: "${fivegsim_path:files/lte_processors.tgff}"

simulation_type:
  _target_: fivegsim.simulation.FiveGSimulation.from_hydra
  trace_file: ${trace_file}
  task_file: ${task_file}

simtrace:
  file: "trace.json"
  app: False
  platform: True
  load:
    granularity: 100000000  # every 100us
    time_frame: 10000000000  # consider the load of the last 10ms

stats: "stats.csv"
load_balancer: False
