# @package _global_
simulation_type:
  _target_: fivegsim.simulation.FiveGSimulation.from_hydra

simtrace:
  file: "trace.json"
  app: False
  platform: True
  load:
    granularity: 100000000  # every 1ms
    time_frame: 10000000000  # consider the load of the last 10ms

fiveg:
    traces: "../../../../../fivegsim/fivegsim/slicedtrace30BS.txt"
    tasks: "../../../../../fivegsim/fivegsim/lte_processors.tgff"
