# @package _global_
trace_file: ???
task_file: "${fivegsim_path:files/proc_file.csv}"

simulation_type:
  _target_: fivegsim.simulate.FiveGSimulation.from_hydra
  trace_file: ${trace_file}
  task_file: ${task_file}

simtrace:
  file: "trace.json"
  app: False
  platform: True
  load:
    granularity: 100000000  # every 100us
    time_frame: 10000000000  # consider the load of the last 10ms

load_balancer: False
tetris_runtime: False
tetris_iterative: False
stats_applications: "stats.csv"
stats_activations: "stats_manager.csv"

pareto_metadata_simulate: False
pareto_time_scale: 1.0
pareto_time_offset: 0
