# @package _group_
_target_: fivegsim.simulation.FivegTrace.from_hydra
prbs: ${phybench.prbs}
layers: ${phybench.layers}
modulation_scheme: ${phybench.modulation_scheme}
task_file: ${phybench.task_file}
